version: "3.9"

networks:
  lemp:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.16.254.0/24"

services:

  mysql:
    build: ./docker/mysql
    #image: mysql:8.0
    networks:
      - lemp
    volumes:
      - mysqldata:/var/lib/mysql
    env_file:
      - ./mysql.env
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
      interval: 10s
      retries: 10

  phpfpm:
    build: ./docker/phpfpm
    #image: drupal:9.3.13-php8.0-fpm-alpine3.15
    networks:
      - lemp
    volumes:
      - drupaldata:/var/www/html
    depends_on:
      mysql:
        condition: service_healthy

  nginx:
    #image: nginx:1.22-alpine
    build: ./docker/nginx
    networks:
      - lemp
    ports:
      - 80:80
      - 443:443
      - 8080:8080
      - 4343:4343
    volumes:
      - drupaldata:/var/www/html
      - phpmyadmindata:/var/www/phpmyadmin
    depends_on:
      - phpfpm


  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5-fpm-alpine
    networks:
      - lemp
    environment:
      PMA_HOST: mysql
    volumes:
      - phpmyadmindata:/var/www/html
    depends_on:
      mysql:
        condition: service_healthy


volumes:
  mysqldata:
  drupaldata:
  phpmyadmindata:
