Vagrant.configure("2") do |config|
#
#
#---------------------- NODES -------------------------------------
  (1..3).each do |i|
    config.vm.define "node-00#{i}" do |node|
      node.vm.box = "ubuntu/jammy64"
      node.vm.hostname = "node-00#{i}"

      node.vm.synced_folder ".", "/vagrant", disabled: true

      node.vm.network "public_network", bridge: "wlp3s0",
       ip: "192.168.0.20#{i}",
       netmask:"255.255.255.0",
       gateway: "192.168.0.1"

      node.vm.provision "shell", inline: <<-SHELL
        atp-get update
        apt-get install nfs-common -y
        
        curl -fsSL https://get.docker.com -o get-docker.sh
        sh get-docker.sh
        usermod -aG docker vagrant
      SHELL

      node.vm.provider "virtualbox" do |virtualbox|
        virtualbox.name = "node-00#{i}"
        virtualbox.memory = "2048"
        virtualbox.cpus = 6

        virtualbox.default_nic_type = "82543GC"
      end # end provider

    end # end define

  end # end loop

#---------------------------------------------------------------------#

end
